version: '3'
services:
 desafio:
  build:
    context: ./images-docker
    dockerfile: DockerfileWEB
  container_name: desafioweb
  restart: always
  ports:
    - "80:80"
  volumes:
    - "./volumes:/home/desafio/web"
  depends_on:
    - "desafiodb"
  command: bash -c "npm rebuild && npm install && npm start"
 
 desafiodb:
  container_name: desafiodb
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - "./volumes/data:/data/db"
  restart: always